version: '3.9'

services:
    db:
      image: postgis/postgis:15-3.3
      container_name: db
      env_file: 
        - .env
      ports: 
        - 5434:5432
      volumes: 
        - db-data:/var/lib/postgresql
      networks:
        - pg
      restart: on-failure
      healthcheck:
        test: "exit 0"

    api:
      container_name: api
      restart: always
      build: ./api
      env_file: 
        - .env
      networks:
        - pg
      ports: 
        - 8080:80

volumes:
  db-data:
  db-backups:

networks:
  pg: 