version: '3.9'

services:
    climate:
        container_name: climate
        environment:
            - IN_DOCKER=TRUE
        build: ./app
        restart: always
        env_file:
            - ./.env
        # ports:
        #     - "3838:3838"
        expose:
        - "3838"
        networks:
            - web

    blm_api:
        container_name: blm_api
        restart: always
        build: ./api
        env_file:
            - ./.env
        # ports:
        #     - "80:80"
        expose: 
            - "80"
        networks:
            - web

volumes:
    db-data:
    db-backups:

networks: 
    web:
        external: true
