version: '3.9'

services:
    db:
        container_name: db
        image: postgres:15
        env_file: 
            - ./.env
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./db/postgres.conf:/etc/postgresql/postgresql.conf
            - ./db/data:/data

        command: postgres -c config_file=/etc/postgresql/postgresql.conf
        restart: on-failure
        healthcheck:
            test: "exit 0"
        networks:
            - web

    climate:
        container_name: climate
        build: ./app
        restart: always
        env_file:
            - ./.env
        expose:
            - "3838"
        networks:
            - web

volumes:
    db-data:
    db-backups:

networks: 
    web:
        external: true
