version: '3.9'

services:
    db:
        container_name: db
        image: postgres:15
        env_file: 
            - ./.env
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./db/postgres.conf:/etc/postgresql/postgresql.conf
            - ./db/data:/data

        command: postgres -c config_file=/etc/postgresql/postgresql.conf
        restart: on-failure
        healthcheck:
            test: "exit 0"
        networks:
            - web

    climate:
        container_name: climate
        environment:
            - IN_DOCKER=TRUE
        build: ./app
        restart: always
        env_file:
            - ./.env
        # ports:
        #     - "3838:3838"
        expose:
        - "3838"
        networks:
            - web

    blm_api:
        container_name: blm_api
        restart: always
        build: ./api
        env_file:
            - ./.env
        # ports:
        #     - "80:80"
        expose: 
            - "80"
        networks:
            - web

volumes:
    db-data:
    db-backups:

networks: 
    web:
        external: true
